server:
  port: 9090

spring:
  application:
    name: user-management-with-redis

  redis:
    database: 0
    host: localhost
    port: 6379
    password: ""


security:
  token-key: 123456
  token-type: Bearer
  separator: --
  validity: 10000000
  authorities-key: authorities

